version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.1.4
    - 3.3.1
  - dependency-name: commitlint
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: eslint
    versions:
    - 7.10.0
    - 7.22.0
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.1
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.2
  - dependency-name: "@types/express-serve-static-core"
    versions:
    - 4.17.14
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: nexus
    versions:
    - 0.26.1
