#####################################################
# Application settings
#####################################################
app:
  processing:
    nbThreads: 1
  rabbitMQ:
    url: amqp://localhost
    retry: true
