on: push
name: Publish mainline
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install
        run: yarn install --frozen-lockfile
      - name: ls
        run: ls -l apps/webapp/node_modules
      - name: ls
        run: ls -l apps/webapp/node_modules/@howdypix
      - name: ls
        run: ls -l apps/webapp/node_modules/@howdypix/*
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: e2e
        run: yarn test:e2e
