on: push
name: Publish mainline
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Cache yarn root
        uses: actions/cache@preview
        with:
          path: ${{ format('{0}{1}', github.workspace, '/node_modules') }}
          key: ${{ runner.os }}-yarn-root-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-root-
      - name: Cache yarn server
        uses: actions/cache@preview
        with:
          path: ${{ format('{0}{1}', github.workspace, '/apps/server/node_modules') }}
          key: ${{ runner.os }}-yarn-server-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/server/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-server-
      - name: Cache yarn webapp
        uses: actions/cache@preview
        with:
          path: ${{ format('{0}{1}', github.workspace, '/apps/webapp/node_modules') }}
          key: ${{ runner.os }}-yarn-webapp-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/webapp/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-webapp-
      - name: Cache yarn worker
        uses: actions/cache@preview
        with:
          path: ${{ format('{0}{1}', github.workspace, '/apps/worker/node_modules') }}
          key: ${{ runner.os }}-yarn-worker-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/worker/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-worker-
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: End-to-end tests
        run: yarn test:e2e
