name: Release

on:
  push:
    tags: ["v*"]

jobs:
  github_release:
    name: Trigger GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Create a new release
        run: GITHUB_RELEASE_TOKEN=${{GITHUB_RELEASE_TOKEN}} node ./scripts/gh-release.js