#####################################################
# Application settings
#####################################################
app:
  webapp:
    port: 3000
    baseUrl: http://localhost:3000

  api:
    baseUrl: http://localhost:3004